# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rh',
            name='rh_images',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rh',
            name='rh_title_image',
            field=models.TextField(default=''),
        ),
    ]
