# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privince', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rh_name', models.TextField()),
                ('rh_phone', models.TextField()),
                ('rh_mobile', models.TextField()),
                ('rh_email', models.TextField()),
                ('rh_postcode', models.TextField()),
                ('rh_location_id', models.TextField()),
                ('rh_type', models.TextField()),
                ('rh_factory_property', models.TextField()),
                ('rh_person_in_charge', models.TextField()),
                ('rh_establishment_time', models.TextField()),
                ('rh_floor_surface', models.TextField()),
                ('rh_building_area', models.TextField()),
                ('rh_bednum', models.TextField()),
                ('rh_staff_num', models.TextField()),
                ('rh_for_persons', models.TextField()),
                ('rh_charges_extent', models.TextField()),
                ('rh_special_services', models.TextField()),
                ('rh_contact_person', models.TextField()),
                ('rh_address', models.TextField()),
                ('rh_url', models.TextField()),
                ('rh_transportation', models.TextField()),
                ('rh_inst_intro', models.TextField()),
                ('rh_inst_charge', models.TextField()),
                ('rh_facilities', models.TextField()),
                ('rh_service_content', models.TextField()),
                ('rh_inst_notes', models.TextField()),
                ('rh_ylw_id', models.TextField()),
            ],
        ),
    ]
