# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rh',
            name='rh_bednum_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rh',
            name='rh_charges_max',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='rh',
            name='rh_charges_min',
            field=models.IntegerField(default=0),
        ),
    ]
