# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHModel', '0002_auto_20180412_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privince', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
            ],
        ),
    ]
